### PR TITLE
Add Blog Post - micro and normal

### PR DESCRIPTION
**Pull request by PrivacyOsint2**
## What this Pull Request (PR) does
Add Blog Post - mirco and normal.

Update / improved tweet pattern.

### CODE REVIEW

**Comment by MattBash17** [comment]
Cool! Just fix the typo in the micro pattern, currently it reads "mirco"

**Comment by PrivacyOsint2** [comment]
@MattBash17 
Thank You!

**Comment by MichaelCade** [comment]
@PrivacyOsint2 Which model do you run this against, I have tried the pre PR merged version and this one and I am getting a long long summary and nothing like a tweet summary using Ollama (Mistral & Llama3) 

Curious if you have an example using OpenAI or if you are using local models as well on this

**Comment by danielmiessler** [comment]
Please use the normal naming convention of starting with a verb. Thank you!

**Pull request closed without merging**
