### PR TITLE
Remove spurious empty file left by commit eaa1667

### PR DESCRIPTION
**Pull request by ksylvan**
## What this Pull Request (PR) does
Remove the empty `analyzepaper.txt` file on the top level directory of the fabric repo, introduced by this commit: eaa1667

The file is not referenced anywhere else.

### CODE REVIEW

**Comment by ksylvan** [comment]
@xssdoctor please merge this PR to remove `fabric/analyzepaper.txt` - Thank you.

**Comment by xssdoctor** [comment]
I just deleted the file. Thanks!

**Comment by ksylvan** [comment]
@xssdoctor How about also removing the crewi related `test.yaml`? This also does not get mentioned anywhere else.

**Comment by xssdoctor** [comment]
done

**Pull request closed without merging**
