### PR TITLE
Update translate pattern to use curly braces

### PR DESCRIPTION
**Pull request by iqbalabd**
## What this Pull Request (PR) does
Updates the pattern for translation to use curly braces so we can insert the target language as a parameter on the command line, i.e

`$ cat my-english-text.md | fabric -v=lang_code:ja-jp -p translate` 

## Related issues
Resending my PR that removes the version files reference [here].(https://github.com/danielmiessler/fabric/pull/1219)

### CODE REVIEW

**Comment by sdnnvs** [comment]
The "translate" pattern seems to be suffering from an error. The error return indicates the absence of the lang_code. For Brazilian Portuguese, I passed the parameters pt, pt-br, pt_br, with and without "".

**Comment by iqbalabd** [comment]
> The "translate" pattern seems to be suffering from an error. The error return indicates the absence of the lang_code. For Brazilian Portuguese, I passed the parameters pt, pt-br, pt_br, with and without "".

I cannot replicate this. Using `pt-br` and `pt` correctly outputs my English text into Portuguese.

Can you confirm you have run `fabric --updatepatterns` to update your patterns to the latest version and the `translate` pattern you have contains the `lang_code`?

**Comment by sdnnvs** [comment]
fabric --updatepatterns ok. 

image

**Comment by iqbalabd** [comment]
@sdnnvs You need to specify the `lang_code` parameter, so try doing this:

`pbpaste|fabric -v=lang_code:pt-br -p translate`

**Comment by sdnnvs** [comment]
> @sdnnvs You need to specify the `lang_code` parameter, so try doing this:
> 
> `pbpaste|fabric -v=lang_code:pt-br -p translate`

It works now: pbpaste|fabric -v=lang_code:pt-br -p translate

Thx

**Pull request merged**
