### PR TITLE
Better gui with streamlit framework

### PR DESCRIPTION
**Pull request by kayozxo**
## Introduction
Fabric is a command line tool that utilizes patterns (prompts) to improve the output from an AI model. With this pull request, I have developed a web application using Streamlit, which allows users to interact with Fabric in a more user-friendly way. The app features include:

1. Selecting and setting up available models for use by the AI engine
2. Selecting prompts (patterns) according to individual preferences
3. Integrating the ability to update patterns, set default models, and display responses with real-time updates
4. Streamlined user experience in generating accurate responses from the selected model
5. Easy debugging and error handling for better development process

This pull request aims to enhance the Fabric CLI tool by providing an interactive web interface while maintaining the functionality and usability of the original command line version. The app.py file contains Streamlit code that is responsible for creating this UI, whereas utils.py is borrowed from another folder but modified to suit my needs in terms of returning outputs, etc.

## Changes Made:
Below are detailed changes made in the project to create the Streamlit application and integrate it with the utils.py file:

### File: app.py

1. Import statements were added for the streamlit library used for building web applications.
2. Set up a Streamlit-based layout, title page, and sidebar configurations as described in the given code block above.
3. Implemented features such as model selection, pattern/prompt selection, user input handling, response generation using AI models, updation of patterns, setting default model, etc.
4. Added Streamlit components like chat_input and stream_message for interactive user-AI conversation.
5. Enhanced error messages, status updates, and debugging information to provide a better understanding of the application's flow and potential errors during execution.
6. Modified code structure to adhere to clean coding practices and enhance readability.
7. Added appropriate comments throughout the file for clarity on functionality and usage.

### File: utils.py

1. Adjusted methods in Update, Standalone and Setup classes from the Fabric CLI tool to accommodate Streamlit's execution flow.
2. Modified return types of these utility functions, especially for asynchronous operations, ensuring compatibility with the new application architecture.
3. Comments were added throughout the file explaining changes made to utilizing it within a Streamlit-based web app.

> I created this pull-request description using the `write_pull_request` pattern through the streamlit web interface.

## Screenshots
image
image

## WIP
- I am still working on remaining features like the YouTube transcribe feature and performing patterns on that transcript, audio file transcribe feature, etc.

### CODE REVIEW

**Comment by xssdoctor** [comment]
I absolutely love this. However we are just about to transition to the go version. This will also work well with that version but let's wait to push this until then. I may just take this for the go version though. It's fantastic and way better than the web frontend I made

**Comment by kayozxo** [comment]
> I absolutely love this. However we are just about to transition to the go version. However this is fantastic and way better than the web frontend I made

Thank you @xssdoctor, I really appreciate the feedback that the current implementation is better than the previous web frontend.

**Comment by kayozxo** [comment]
# Improved UI and UX

- Added **tabs** to navigate between different features, like YouTube transcript, audio transcript and settings (I might remove the settings tab cause all required settings are on the sidebar)
- Changed the colour scheme of the entire app
- Adapted to ShadCn UI style

image

> Please feel free to give feedback and suggestions. They are much appreciated!

**Comment by kayozxo** [comment]
# YouTube Feature Works Now!

- Asking AI to perform a pattern on a YouTube transcript works now!
- I changed the UI of the buttons back to streamlit's default buttons due to some issues with the streamlit-shadcn-ui library.

image
image

**Comment by PrivacyOsint2** [comment]
How do you get the gui/ ui working? I have tried but I need a better manual /docs.

**Comment by kayozxo** [comment]
> How do you get the gui/ ui working? I have tried but I need a better manual /docs.

Sure. Let me add a requirement.txt file and get back to you with better docs.

**Comment by kayozxo** [comment]
1. Clone the repository from the better-gui branch `git clone -b better-gui https://github.com/kayozxo/fabric.git`
2. `cd` into the repository, then paste this `cd installer/client/streamlit`
3. Now install all the required packages using `pip install -r requirements.txt`
4. After installation, stay in the same directory and run `streamlit run app.py`

@PrivacyOsint2 Hope this will help!

**Comment by PrivacyOsint2** [comment]
@kayozxo I installed it from scratch because I was getting error with older versions of fabric. After I installed fresh I could get the gui to work, now there is an error.
I only installed youtube api version 3 api key. I don't have or need any other api keys. I use ollama.


ModuleNotFoundError: No module named 'openai'

File "/home/mrwaste/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/home/mrwaste/fabric/installer/client/streamlit/app.py", line 2, in <module>
    from utils import Standalone, Update, Alias, Setup, Transcribe
File "/home/mrwaste/fabric/installer/client/streamlit/utils.py", line 3, in <module>
    from openai import OpenAI, APIConnectionError

**Comment by PrivacyOsint2** [comment]
@kayozxo I installed it from scratch because I was getting error with older versions of fabric. After I installed fresh I could get the gui to work, now there is an error.
I only installed youtube api version 3 api key. I don't have or need any other api keys. I use ollama inside docker.

ModuleNotFoundError: No module named 'openai'

File "/home/user/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/home/user/fabric/installer/client/streamlit/app.py", line 2, in <module>
    from utils import Standalone, Update, Alias, Setup, Transcribe
File "/home/user/fabric/installer/client/streamlit/utils.py", line 3, in <module>
    from openai import OpenAI, APIConnectionError

**Comment by PrivacyOsint2** [comment]
Feature Request:

Could you build one more pipe / pattern to pattern.
For example:

yt --transcript https://www.youtube.com/watch?v= | fabric --model llama3:8b -sp write_essay | fabric --model llama3:8b -sp extract_wisdom

**Comment by kayozxo** [comment]
> @kayozxo I installed it from scratch because I was getting error with older versions of fabric. After I installed fresh I could get the gui to work, now there is an error. I only installed youtube api version 3 api key. I don't have or need any other api keys. I use ollama inside docker.
> 
> ModuleNotFoundError: No module named 'openai'
> 
> File "/home/user/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script exec(code, module.**dict**) File "/home/user/fabric/installer/client/streamlit/app.py", line 2, in from utils import Standalone, Update, Alias, Setup, Transcribe File "/home/user/fabric/installer/client/streamlit/utils.py", line 3, in from openai import OpenAI, APIConnectionError

There are a total of 3 different API keys for YouTube. The one you should be giving is **YouTube Data API v3**. And also just install OpenAI with `pip install openai` and the issue will go away, you don't have to use OpenAI models, it's up to you.

**Comment by kayozxo** [comment]
> Feature Request:
> 
> Could you build one more pipe / pattern to pattern. For example:
> 
> yt --transcript https://www.youtube.com/watch?v= | fabric --model llama3:8b -sp write_essay | fabric --model llama3:8b -sp extract_wisdom

@PrivacyOsint2 As the fabric team is migrating to the GO version, I have decided to stop developing this GUI. If I get more requests to re-open the pr and for other features, I will happily reopen it and continue developing this! 🙂

**Comment by kayozxo** [comment]
@PrivacyOsint2 I have updated the `requirements.txt` file, run that again using `pip install -r requirements.txt`; now you should be error-free.

**Pull request closed without merging**
