### PR TITLE
Building an Astro/React Web UI for Fabric

### PR DESCRIPTION
**Pull request by timothyjoh**
## What this Pull Request (PR) does

Added a `web` directory under `installer/client` where I can create and update a WebUi to run locally.
Ideally we are opening some simple fabric usage for users who would prefer this over the CLI

Update: Added a LocalStorage memory function to save previous queries. Much improved over the drawer

## Related issues
none

## Screenshots
Provide any screenshots you may find relevant to facilitate us understanding your PR.
Screenshot 2024-06-02 at 2 27 57 PM

Screenshot 2024-06-02 at 2 28 18 PM

Screenshot 2024-06-02 at 5 07 12 PM
Screenshot 2024-06-02 at 5 07 28 PM

### CODE REVIEW

**Comment by timothyjoh** [comment]
Tested on another machine this morning, and realized there were some missing files in my `src/lib` folder due to the `.gitignore` at the root. Pushed these up.

Sometimes the Pattern Selector is getting out-of-sync with the form. I will work on this

**Comment by timothyjoh** [comment]
Added more:
1. Ability to change the default model
2. Ability to adjust the temperature with the slider

As I am adding more, I feel like there will be a better UI to emerge out of this.

**Comment by danielmiessler** [comment]
This is super exciting but we're moving to Go soon and we need to have a big convo about this. Let's close this for now but re-surface in a few weeks with @xssdoctor .

**Comment by danielmiessler** [comment]
And THANK YOU!

**Comment by lionardben211** [comment]
excelent

**Comment by lionardben211** [comment]
How can I run that?

**Comment by timothyjoh** [comment]
No problem, I'll keep it going meanwhile and I'm looking forward to the GO conversion

**Comment by timothyjoh** [comment]
> How can I run that?

you can run it with `fabric --web` command, as long as you pull from this branch and reinstall with `pipx install . --force`

**Comment by LaBalaDeOro** [comment]
@timothyjoh have you tried out the Go version of fabric? If so, have you thought anymore about revisiting this excellent PR?

**Comment by mayphilc** [comment]
doesnt work, fabric isnt a command

**Pull request closed without merging**
