### PR TITLE
Get OLLAMA models to work in Windows (both native and WSL).

### PR DESCRIPTION
**Pull request by ksylvan**
# Summary

Fix for https://github.com/danielmiessler/fabric/issues/314 - Ollama now functions perfectly on Windows (both natively and in the WSL environment).

# Files Changed

- `installer/client/cli/utils.py`: This file contains utility functions and classes for the Fabric CLI.

# Code Changes

1. Removed the unused `re` import and added the `youtube_transcript_api` import (needed in the Transcribe class) :
   ```python
   - import re
   import shutil
   + from youtube_transcript_api import YouTubeTranscriptApi
   ```

2. Removed `host` parameter from the `AsyncClient().chat()` calls in the `localChat()` and `localStream()` methods of the `Standalone` class. This was causing failures when using `--remoteOllamaServer`  since Ollama's `AsyncClient().chat()` does not take a `host` parameter.
   ```python
   - response = await AsyncClient(host=host).chat(model=self.model, messages=messages, host=host)
   + response = await AsyncClient(host=host).chat(model=self.model, messages=messages)
   ```
   ```python
   - async for part in await AsyncClient(host=host).chat(model=self.model, messages=messages, stream=True, host=host):
   + async for part in await AsyncClient(host=host).chat(model=self.model, messages=messages, stream=True):
   ```

3. Added support for specifying a remote Ollama server when listing available models in the `listModels()` method of the `Standalone` class:
   ```python
   + if self.args.remoteOllamaServer:
   +     client = ollama.Client(host=self.args.remoteOllamaServer)
   +     default_modelollamaList = client.list()['models']
   + else:
   +     default_modelollamaList = ollama.list()['models']
   ```

# Reason for Changes

1. The `re` import was removed because it was not being used in the code, and the `youtube_transcript_api` import was added because it is being used later in the file.

3. The `host` parameter was removed from the `AsyncClient().chat()` calls. Now these calls work as intended.

4. The changes to the `listModels()` method fixes the code when trying to list models.

# Impact of Changes

Fixed remote Ollama server usage problems and bugs. Specifically, in WSL environment on Windows, where the Ollama server is running on the native host, it makes it possible to access the model list and to use Ollama local models.

# Test Plan

To test these changes, the following steps were performed:

1. Verified that the Fabric CLI still functions correctly after removing the unused `re` import and adding the `youtube_transcript_api` import.

2. Tested the `localChat()` and `localStream()` methods with and without specifying a host to ensure that they work as expected.

3. Tested the `listModels()` method with and without specifying a remote Ollama server to ensure that it retrieves the correct list of available models. This was done both in native Windows and WSL.

### CODE REVIEW

**Comment by danielmiessler** [comment]
@xssdoctor how does this look? Will this break anything?

**Comment by ksylvan** [comment]
@danielmiessler I tested it on my Linux Ubuntu and MacOS laptop too.

**Comment by ksylvan** [comment]
I just merged the latest commits and re-tested. All is working correctly in Windows (native), Windows WSL, Linux, and MacOS. @danielmiessler @xssdoctor

**Comment by ksylvan** [comment]
> @xssdoctor how does this look? Will this break anything?

@xssdoctor @danielmiessler I've tested this in Linux, MacOS, and Windows (native), and Windows WSL.

**Comment by ksylvan** [comment]
Hi @xssdoctor @danielmiessler - Updated the branch again with the latest from upstream. All my testing still works. This is a safe change that has to happen to make OLLAMA local models work on Windows.

**Comment by xssdoctor** [comment]
done

**Comment by defconhaya** [comment]
Still same error. I've done a clean install with latest commits, both in WSL and native windows.
`curl http://localhost:11434
Ollama is running`
` fabric --remoteOllamaServer http://localhost:11434 --listmodels
Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401`

Is there any config file where I need to add something ?

**Comment by epeuu** [comment]
Hey friend @ksylvan,

I am writing to inform you about an issue I am currently experiencing after following your instructions from pull [#315](https://github.com/danielmiessler/fabric/pull/315).

Upon completing the steps you provided, I checked if everything was set as it should be and found that all the settings were correct (image attached for reference).

However, despite having properly implemented the suggested changes, I am still encountering issues. One such issue is the message:

`Error: Error code: 404 - {'error': {'message': 'The model `llama3` does not exist or you do not have access to it.', 'type':'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Error code: 404 - {'error': {'message': 'The model `llama3` does not exist or you do not have access to it.', 'type':'invalid_request_error', 'param': None, 'code': 'model_not_found'}}`

I have double-checked my work and verified that the issue persists.
I am now reaching out to you for assistance in finding a solution.

Looking forward to your insights on this issue.
fabric

**Comment by ksylvan** [comment]
The OLLAMA models need to be accessed by their full name, so if you are trying to use a local llama3 model, it would likely be llama3:latest, not "llama3".

```text
$ fabric --pattern ai --text 'Why is the sky blue?' -m llama3:latest
Here's an answer in 3-5 Markdown bullets of 10 words each:

* The sky appears blue because of a phenomenon called Rayleigh scattering.
* When sunlight enters Earth's atmosphere, it encounters tiny molecules of gases like nitrogen and oxygen.
* These molecules scatter the light in all directions, but they scatter shorter (blue) wavelengths more than longer (red) wavelengths.
* This is why our eyes perceive the sky as blue during the daytime.
```

Kayvan Sylvan
Technical Leadership, Software Architect, Full Stack Engineering.
https://www.linkedin.com/in/kayvansylvan/

**Pull request merged**
