### PR TITLE
Create coding_master pattern

### PR DESCRIPTION
**Pull request by helloIlovegimkit**
## What this Pull Request (PR) does
This simply adds a coding_master pattern (and no I am not a troll)

## Screenshots
Provide any screenshots you may find relevant to facilitate us understanding your PR.

image
image

### CODE REVIEW

**Comment by helloIlovegimkit** [comment]
image

I used part of the extract_wisdom pattern to illustrate a better response

**Comment by helloIlovegimkit** [comment]
And of course I had to add networkchuck in there

**Comment by kevnk** [comment]
I just saw this and tried to use it this morning and I get "pattern not found" - I see it in the `patterns/` directory but not in the list of available patterns when I run `fabric -l`

I'm I missing something?

**Comment by helloIlovegimkit** [comment]
> I just saw this and tried to use it this morning and I get "pattern not found" - I see it in the `patterns/` directory but not in the list of available patterns when I run `fabric -l`
> 
> I'm I missing something?

Have you ran fabric --update to update your patterns

```
fabric --update
```

**Comment by kevnk** [comment]
> Have you ran fabric --update to update your patterns

That worked! I thought I just had to pull the latest from github. Thanks!

**Pull request merged**
