### PR TITLE
Electron App Packaging

### PR DESCRIPTION
**Pull request by danigoland**
## What this Pull Request (PR) does

- Makes it possible to package the GUI into a DMG/EXE file.
- Modified the `getOpenAIClient` function to only create a new `OpenAI` object if one does not exist, otherwise it will return the object that is already initialized

## Related issues
Please reference any open issues this PR relates to in here.

## Screenshots
image
image
image

### CODE REVIEW

**Comment by danielmiessler** [comment]
Amazing!

@xssdoctor this is the guy I told you you should meet. He's got great ideas about how to move to binaries eventually. And this is along that path.

**Comment by xssdoctor** [comment]
Hey. sorry ive made a lot of changes to the repo since this pull request (sorry i'm so late). Do you mind resolving the conflicts before i merge? I would do it but i'm afraid im going to mess the whole thing up (which i seem to do every time i mess with the poetry environment

**Comment by danigoland** [comment]
@xssdoctor Yeah no worries, I'll take care of the conflicts 👍

**Review by thereallori — APPROVED** [review]

**Comment by danielmiessler** [comment]
This is amazing! We're moving to Go soon so let's revisit this once we migrate.

**Pull request closed without merging**
